# Generated by Django 3.2.7 on 2021-10-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.CharField(max_length=500, verbose_name='Comentar'),
        ),
    ]
