# Generated by Django 3.2.7 on 2021-11-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0002_alter_comentario_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='obs',
            field=models.TextField(blank=True, max_length=500, verbose_name='Observação'),
        ),
    ]
